name: network_cache_interceptor
description: "NetworkCacheInterceptor is a custom interceptor designed to optimize network requests by integrating caching functionality into your application using the Dio library."
version: 1.3.4
homepage: "https://github.com/JaysonKhan/network_cache_interceptor.git"
repository: "https://github.com/JaysonKhan/network_cache_interceptor"
license: 'MIT'

environment:
  sdk: ">=3.5.3 <3.8.0" # Supports Dart 3.5.3 to 3.7.x
  flutter: ">=2.0.0" # Minimum Flutter version updated

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0 # Defined a stable version instead of `any`

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Updated to a stable version